DB_PATH                 = 'MainDatabaseVet'  #ссылка на базу даных для драйвера, по умолчанию 'MainDatabaseVet'
EXCEL_TEMPLATE_PATH     = 'template.xlsx' #путь к шаблону документа, по умолчанию 'template.xlsx'
EXCEL_HEADER_ROWS       = 5 #необходимый параметр для обработчика Pandas, по умолчанию 5
MAIN_REPORT_PAGE        = 'Отчет' #имя листа документа в рекзультирующей электронной таблице
WRAP_COLUMNS            = ['is_conditions_good', 'specie'] #параметры группировки для документа , по умолчанию ['is_conditions_good', 'specie']
SAVE_DIR                = 'C:/TAURUS' #папка для созранения отчётов, по умолчанию 'C:/TAURUS'
NAMES_TXT_PATH          = 'names.txt' #файло реквизитов для документа, по умолчанию 'names.txt'
DATABASE_DRIVER_QT      = 'QSQLITE'  #Используемый QSQL драйвер, по умолчанию 'QSQLITE'
DATABASE_DRIVER_PANDAS  = 'sqlite'   #Используемый pandas драйвер, по умолчанию 'sqlite'