DB_PATH                 = 'MainDatabaseVet'
EXCEL_TEMPLATE_PATH     = 'template.xlsx'
EXCEL_HEADER_ROWS       = 5
MAIN_REPORT_PAGE        = 'Отчет'
WRAP_COLUMNS            = ['is_conditions_good', 'specie']
SAVE_DIR                = 'C:/TAURUS'
NAMES_TXT_PATH          = 'names.txt'
DATABASE_DRIVER_QT      = 'QSQLITE'  #unused
DATABASE_DRIVER_PANDAS  = 'sqlite'   #unused
DETAILS_FILE            = 'names.txt'